version: '3'

services:
  database:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: clodoaldo
      POSTGRES_HOST: 0.0.0.0

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 7000:8080